### PR TITLE
Typescript definitions

### PR DESCRIPTION
**Pull request by robjtede**
Not properly tested for every function but most of the signatures are similar enough to guess.

### CODE REVIEW

**Comment by toniov** [comment]
Thanks!

Let me take a look when I have some time.

**Comment by robjtede** [comment]
Any chance of this being looked at ?

**Comment by toniov** [comment]
Sorry didn't use TypeScript before and just procrastinated too long on this.
I took a look to how declaration files work and it looks good to me.

Could you test the rest of functions?

**Comment by AleksandrGol** [comment]
I was used and tested. Looks good to me.

**Comment by toniov** [comment]
I'll merge it and release it as a patch 👍

**Comment by toniov** [comment]
Shipped in `1.1.7`.

Thanks @robjtede and @AleksandrGol !

**Pull request merged**
